config/routes.rb
Rails.application.routes.draw do

  root 'epicenter#feed'

  get 'all_users' => 'epicenter#all_users'
  get 'show_user' => 'epicenter#show_user'
  get 'now_following' => 'epicenter#now_following'
  get 'unfollow' => 'epicenter#unfollow'
  get 'tag_tweets' => 'epicenter#tag_tweets'
  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'

  devise_for :users
  resources :tweets

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  # associations
  belongs_to :user
  has_many :tweet_tags
  has_many :tags, through: :tweet_tags

  # validations
  validates :message, presence: true
  validates :message, length: {maximum: 140,
  too_long: "too long. Max tweet 140 characters!"}, on: :create
  # see form partial to customize further
  # hooks
  after_validation :apply_link, on: :create
  before_validation :link_check, on: :create
  # link_checks first, then does the other validations above. The before_validation is also called a "hook"

private
# makes it so that you can't call link_check outside the method - prevents other developers from using your code incorrectly



  def link_check
    check = false
    if self.message.include? "http://"
      check = true
    elsif self.message.include? "https://"
      check = true
    else
      check = false
    end

    if check == true
      arr = self.message.split

      index = arr.map{ |x| x.include? "http"}.index(true)
      # map is a function that takes a block and returns an array with the result of each element mapped to the return value of that block - this line is breaking the message into an array of words and checking to see if any item/word in the array starts with http
      self.link = arr[index]
      # saving that http to the variable self
      if arr[index].length > 23
        arr[index] = "#{arr[index][0..20]}..."
      end
      # if longer than 23 characters, it gets shortened to the first 21 characters with ...

      self.message = arr.join(" ")
    end

    def apply_link
      arr = self.message.split
      index = arr.map { |x| x.include? "http://" }.index(true)
      if index
        url = arr[index]
        # finds the index of the http link and saves it as url
        arr[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
        # target='_blank' opens a new tab for the link
	    end
      self.message = arr.join(" ")
    end

   end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  include TweetsHelper
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # authenticate_user makes it so that you HAVE to be logged in to use this controller

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)
    # slide 7 - change new to create so it will safe the tweet and give it an id
    get_tagged(@tweet)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def get_tagged(tweet)
    # to get tagged, you have to feed it a tweet
    message_arr = tweet.message.split
    # this splits each word of the tweet into an array that you can loop through

    message_arr.each_with_index do |word, index|
      # when using each_with_index, you have to pass it 2 block arguments/parameters, the second of which always refers to the index, no matter what you call it inside the pipes.
      if word[0] == "#"
        tag = Tag.find_or_create_by(phrase: word.downcase)
        # goes across the Tag table to find if the tag already exists and if it doesn't, it creates it.  The find_or_create_by is an ActiveRecord Class method.
        TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)
        message_arr[index] = "<a href= '/tag_tweets?id=#{tag.id}'>#{word}</a>"
      end

    end

    tweet.update(message: message_arr.join(" "))
    # since we took the tweet and turned it into an array to locate the #tags, we have to rejoin the words in the array back into a single string


  end
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :message %>
    <%= form.text_field :message, placeholder: "What's happening?", autofocus: true, class: 'form-control' %>
  </div>


  <%= form.hidden_field :user_id, value: current_user.id %>


  <div class="actions">
    <%= form.submit nil, class: "btn btn-primary" %>
    <!-- adding a button class - the first thing it sees is what will be on the button, so nil makes the button figure it out based on the model we passed to form -->
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="well">
  <p>@<%= link_to tweet.user.username, show_user_path(id: tweet.user_id) %></p>
  <div class="pull-right">
    <span class="glyphicon glyphicon-time"></span>
    <% if tweet.created_at < 1.day.ago %>
      <%= tweet.created_at.strftime('%b%e') %>
    <% else %>
      <%= time_ago_in_words tweet.created_at %> ago
    <% end %>
  </div>
  <p><%= tweet.message.html_safe %></p>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= tweet.user_id %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>Username:</strong>
  <%= @tweet.user.username %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>