config/routes.rb
Rails.application.routes.draw do

  root 'epicenter#feed'

  get 'all_users' => 'epicenter#all_users'
  get 'show_user' => 'epicenter#show_user'
  get 'now_following' => 'epicenter#now_following'
  get 'unfollow' => 'epicenter#unfollow'
  get 'tag_tweets' => 'epicenter#tag_tweets'
  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'

  devise_for :users
  resources :tweets

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  # def feed
  #   @tweets = []
  #
  #   Tweet.all.each do |tweet|
  #     if current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id
  #       @following_tweets.push(tweet)
  #     end
  #   end
  # end
before_action :authenticate_user!
# The following is the same as above, but less code & puts more of the responsibility on the database, which is what it's build for!
  def feed
    @user = current_user
    @tweets = Tweet.where(user_id: current_user.following.push(current_user.id)).order(created_at: :desc)
    set_followers
    # <!-- .joins joins the 3 tables -->
    @trending_phrases = Tweet.where('tweets.created_at > ?', 3.days.ago).joins(:tags).group(:phrase).count
  end

  def show_user
    @user = User.find(params[:id])
  end

  def now_following
    current_user.following.push(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  def unfollow
    current_user.following.delete(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  def tag_tweets
    @tag = Tag.find(params[:id])
  end

  def all_users
    @users = User.all
    # or:
    # User.order(:username)
    # User.order(:name)
    # or whatever order you'd
    # like to put them in
  end

# the following gives the total number of followers
  def following
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if @user.following.include?(user.id)
        @users.push(user)
      end
    end
  end

  def followers
    @user = User.find(params[:id])
    set_followers
    @users = @followers
  end

# when you call a method set_ the point is to set an instance variable
  def set_followers
    @followers = []
    User.all.each do |user|
      if user.following.include?(@user.id)
        @users.push(user)
      end
    end
  end

end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/views/epicenter/_user_list.html.erb
<div class="row">
  <% @users.each do |user| %>
    <div class="col-sm-4">
      <div class="well user-list-wells">
        <div class="row">
          <div class="col-sm-6">
            <%= image_tag user.avatar.url, class: 'img-responsive' %>
          </div>
          <div class="col-sm-6">
            <p>
              <% if current_user.following.include?(user.id) %>
                <%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary unfollow-btn" %>
              <% else %>
                <% if current_user.id != user.id %>
                  <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
                <% end %>
              <% end %>
            </p>
          </div>
        </div>
        <div class="row">
          <%= link_to show_user_path(id: user.id) do %>
            <h3><%= user.name %></h3>
            <p>@<%= user.username %></p>

          <% end %>
          <p>Joined on <%= user.created_at.strftime('%b %d %Y') %></p>
          <p>

            <%= user.bio %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/epicenter/all_users.html.erb
<h1>All Users</h1>
<%= render 'user_list' %>

app/views/epicenter/feed.html.erb
<div class="row">
  <div class="col-sm-3 well">
    <h3><%= link_to current_user.username, show_user_path(id: current_user.id) %></h3>
    <h4>Stats</h4>

    <div class="">
      <%= pluralize current_user.tweets.count, "Tweet" %>
    </div>

    <div class="">
      Following <%= pluralize current_user.following.count, "User" %>
    </div>

    <div class="">
      # of Followers
      <%= pluralize @followers.count, 'Follower' %>

      <!-- each do loop -->
    </div>
  </div>
  <!-- current_user and user_signedin? are devise tools -->

  <div class="col-sm-6">

    <h1>@<%= current_user.username %>'s Tweeter Feed</h1>
    <%= render 'tweets/form', tweet: Tweet.new %>
    <!-- <br> -->
    <% @tweets.each do |tweet| %>
      <%= render tweet %>

    <% end %>
  </div>

  <div class="col-sm-3">
    <div class="well">
      <h4>What's Trending</h4>
      <% @trending_phrases.each do |phrase, count| %>
        <% tag = Tag.find_by(phrase: phrase) %>
<!-- need to finish this -->
        <%= link_to phrase, tag_tweets_path(id: tag.id) %> - <% pluralize count, "tweet" %>
      <% end %>
    </div>
  </div>

</div>

app/views/epicenter/followers.html.erb
<h2><%= @user.name %>'s Followers</h2>
<%= render 'user_list' %>

app/views/epicenter/following.html.erb
<!-- following.html.erb -->
<h2><%= @user.name %> is following:</h2>
<%= render 'user_list' %>

app/views/epicenter/now_following.html.erb
<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<h1>@<%= @user.username %>'s Profile & Tweets</h1>



<div class="row">

  <div class="col-md-3">
    <div class="well">
      <p>
        <% unless @user == current_user %>
          <% if current_user.following.include?(@user.id) %>
            <%= link_to 'Following', unfollow_path(id: @user.id), class: 'btn btn-primary unfollow-btn' %>
          <% else %>
            <%= link_to 'Follow', now_following_path(id: @user.id), class: 'btn btn-primary' %>
          <% end %>
        <% end %>
      </p>
      <!-- ADD AVATAR HERE -->
      <p><%= @user.username %> | <%= @user.name %></p>
      <p><%= @user.location %></p>
      <p><%= @user.bio %></p>
      <p>

      </p>
    </div>
  </div>

  <div class="col-md-6">
    <% @user.tweets.each do |tweet| %>
      <%= render tweet %>
      <!-- <div class="well">
        <p>@<%= tweet.user.username %></p>
        <p><%= tweet.message %></p>
      </div> -->
    <% end %>
  </div>

  <div class="col-md-3">

  </div>

</div>

app/views/epicenter/tag_tweets.html.erb
<div class="row">
  <div class="col-md-3">
    <h3>Showing tweets with tag <%= @tag.phrase %></h3>
  </div>

  <div class="col-md-6">
    <% @tag.tweets.each do |tweet| %>
      <%= render tweet %>
    <% end %>
  </div>

  <div class="col-md-3">

  </div>


</div>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>