config/routes.rb
Rails.application.routes.draw do

  root 'epicenter#feed'

  get 'all_users' => 'epicenter#all_users'
  get 'show_user' => 'epicenter#show_user'
  get 'now_following' => 'epicenter#now_following'
  get 'unfollow' => 'epicenter#unfollow'
  get 'tag_tweets' => 'epicenter#tag_tweets'
  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'

  devise_for :users
  resources :tweets

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweeter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Tweeter', root_path, class: 'navbar-brand' %>
        </div>

        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <% if user_signed_in? %>
                  Hello, <%= current_user.name %>!
                  <ul class="dropdown-menu">
                    <li><a href="/">Home</a></li>
                    <li><%= link_to "All Users", all_users_path %></li>

                    <li role="separator" class="divider"></li>
                    <li><a href="#"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></a></li>

                  </ul>
              <% else %>
                <%= link_to 'Sign in', new_user_session_path %>
                <!-- new_user_session_path comes from devise -->
              <% end %>
            </a>
          </li>
        </ul>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>